// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
/// web       1:761654827254:web:bb8ef31849a537018b34d7
/// android   1:761654827254:android:1795e8dd9ab688b28b34d7
/// ios       1:761654827254:ios:c86ba84035d411998b34d7
/// macos     1:761654827254:ios:cd6128e2382c2a398b34d7
///
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDupup6tdoKpUb7sK_gfzu_VtlYEr64AY8',
    appId: '1:761654827254:web:bb8ef31849a537018b34d7',
    messagingSenderId: '761654827254',
    projectId: 'testsapp-3c0de',
    authDomain: 'testsapp-3c0de.firebaseapp.com',
    storageBucket: 'testsapp-3c0de.appspot.com',
    measurementId: 'G-5JM7ZSE0WC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXsgOCHY90Gy0mzVnzcrWNmA05iKwLJ4c',
    appId: '1:761654827254:android:1795e8dd9ab688b28b34d7',
    messagingSenderId: '761654827254',
    projectId: 'testsapp-3c0de',
    storageBucket: 'testsapp-3c0de.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWlWcpMuHtfFiVhpZYqqvjV2dJ08u8KV4',
    appId: '1:761654827254:ios:c86ba84035d411998b34d7',
    messagingSenderId: '761654827254',
    projectId: 'testsapp-3c0de',
    storageBucket: 'testsapp-3c0de.appspot.com',
    iosBundleId: 'com.example.testAppTut',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWlWcpMuHtfFiVhpZYqqvjV2dJ08u8KV4',
    appId: '1:761654827254:ios:cd6128e2382c2a398b34d7',
    messagingSenderId: '761654827254',
    projectId: 'testsapp-3c0de',
    storageBucket: 'testsapp-3c0de.appspot.com',
    iosBundleId: 'com.example.testAppTut.RunnerTests',
  );
}
